### ISSUE TITLE
Consider Dom event handling

### ISSUE THREAD

**Issue by DylanPiercey** [DylanPiercey/vdo#3]
Reminder to look into adding an event delegator to this library and potentially storing event handler functions (with a weakmaps) on the global vdo.

Potentially set something like 'data-onclick=SOMEUID" to do the lookup in the delegator.

**Comment by DylanPiercey** [comment]
I think implementing in this lib would be out of scope, perhaps make a separate lib.

**Comment by roshanisharma** [comment]
Thanku for sharing this useful information.. I would like to share something too...  
Thinkwik is an expertise driven web and mobile apps Development Company helping businesses achieve their goal through robust and engaging web and mobile presence. To Build real time application, mobile app and website

<a href=http://www.thinkwik.com/node-js-framework-development/>Node Js Development Company</a>
<a href=http://www.thinkwik.com/android-application-development/>Android App Development</a>
<a href=http://www.thinkwik.com/iphone-application-development/>iOS App Development</a>
