### ISSUE TITLE
Pass children as props.children

### ISSUE THREAD

**Issue by sapegin** [DylanPiercey/vdo#5]
To better compatibility with Preact, etc. So both would work:

```js
function foo(props, children) {
	return <div>{children}</div>;
}

function foo(props) {
	return <div>{props.children}</div>;
}
```

What do you think? Will you accept a pull request for that?

**Comment by DylanPiercey** [comment]
I have no issue with this. I'll make a patch later today :).

**Comment by DylanPiercey** [comment]
Alright 4.1.0 will now add children to the attributes.

**Comment by sapegin** [comment]
Awesome! Thanks!

**Comment by sapegin** [comment]
Could you please publish it to npm?

**Comment by DylanPiercey** [comment]
Sorry, thought I did. Will do this in a few hours.

**Comment by DylanPiercey** [comment]
published :).
